_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "student_our_FPN_feature"
  WEIGHTS: "weight/dcadet.pth"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  ROI_HEADS:
    NUM_CLASSES: 4
SOLVER:
  BASE_LR: 0.001
  STEPS: (60000, 80000)
  # MAX_ITER: 90000
  MAX_ITER: 94425
  IMS_PER_BATCH: 2
DATASETS:
  TRAIN: ("voc_2012_train",)
  TEST: ("voc_2012_val",)
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1333
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 1888
  PRECISE_BN:
    ENABLED: True
OUTPUT_DIR: "./checkpoint/DSFUDA"